
name: Run Worker

description: Sets up a Redis Cluster instance needed to run the tests

runs:
  using: composite
  steps:
    - name: Install wait-on plugin
      run: npm i -g wait-on

    - name: Build worker
      run: CI='' pnpm build:worker

    - name: Start worker
      env:
        IN_MEMORY_CLUSTER_MODE_ENABLED: true
      run: cd apps/worker && pnpm start:test &

    - name: Wait on worker
      run: wait-on --timeout=180000 http://localhost:1342/v1/health-check
